mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.mall.dao.model

# ????????????
upload.local.path=D:/uploads/
server.port = 8030
server.servlet.context-path=/mall-server  


spring.application.name=mall-api

config.jwt.header=Authorization
config.jwt.expire=259200
config.jwt.secret=xujinnan13760613080

logging.level.com.mall.dao.mapper=debug

#datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/wxmall?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=123456

logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss} %-5level %logger{50} - %msg%n

pagehelper.helper-dialect=mysql
pagehelper.reasonable=true
pagehelper.support-methods-arguments=true
pagehelper.params=count=countSql
 
# Generator
generator.targetProject=src/main/java
generator.mappers=tk.mybatis.mapper.common.Mapper
generator.javaModel-targetPackage=com.mall.dao.model
generator.sqlMap-targetPackage=mapper
generator.javaClient-targetPackage=com.mall.dao.mapper

upload.server.uuid=f775b389-2d99-f280-cff6-032a8af32ae2
wx.appid=wxe1b4bc6da4e353b0
wx.secret=40c020e43f11463a61cbaec19d1ba673